name: Close inactive issues and PRs
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9.0.0
        with:
          days-before-stale: 30
          days-before-close: 5
          days-before-pr-close: -1
          stale-issue-label: "stale"
          exempt-issue-labels: "awaiting-approval,work-in-progress,dependencies"
          exempt-pr-labels: "awaiting-approval,work-in-progress,dependencies"
          stale-issue-message: "This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days."
          close-issue-message: "This issue was closed because it has been stalled for 5 days with no activity."
          stale-pr-message: "This PR is stale because it has been open 30 days with no activity."
          repo-token: ${{ secrets.GITHUB_TOKEN }}
